
DROP TABLE IF EXISTS cars, dogs, states, glasses, fences;

CREATE TABLE cars (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    make TEXT NOT NULL,
    year INTEGER NOT NULL
);

CREATE TABLE dogs (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    breed TEXT NOT NULL,
    color TEXT NOT NULL
);

CREATE TABLE states (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    abbrev TEXT NOT NULL,
    land_locked BOOLEAN NOT NULL
);

CREATE TABLE glasses (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    rx BOOLEAN NOT NULL,
    tinted BOOLEAN NOT NULL
);

CREATE TABLE fences (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    privacy BOOLEAN NOT NULL,
    material TEXT NOT NULL
);

